"""add app memory_metadata

Revision ID: b57f432effa5
Revises: 09a8d1878d9b
Create Date: 2024-11-18 09:25:56.014892

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b57f432effa5'
down_revision = '09a8d1878d9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memory_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('memory_metadata')
    # ### end Alembic commands ###
