"""add model_person

Revision ID: 22be86a359c2
Revises: 6e957a32015b
Create Date: 2024-08-02 03:08:16.196597

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '22be86a359c2'
down_revision = '6e957a32015b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_person',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('habbit', sa.Text(), nullable=True),
    sa.Column('values', sa.Text(), nullable=True),
    sa.Column('knowledge', sa.Text(), nullable=False),
    sa.Column('mbti', sa.Text(), nullable=True),
    sa.Column('values_deal', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=100), nullable=True),
    sa.Column('audio_train_path', sa.String(length=100), nullable=True),
    sa.Column('audio_model_s_path', sa.String(length=100), nullable=True),
    sa.Column('audio_model_g_path', sa.String(length=100), nullable=True),
    sa.Column('audio_reference_path', sa.String(length=100), nullable=True),
    sa.Column('audio_reference_text', sa.Text(), nullable=True),
    sa.Column('appid', models.StringUUID(), nullable=True),
    sa.Column('create_time', sa.Date(), nullable=True),
    sa.Column('update_time', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('big5', sa.Text(), nullable=True),
    sa.Column('knowledge_path', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='model_person_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('model_person')
    # ### end Alembic commands ###
