"""add_img_conversation_plan_detail

Revision ID: 6943145e12f7
Revises: ad2b4b4e5eb8
Create Date: 2024-03-22 16:32:15.749634

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6943145e12f7'
down_revision = 'ad2b4b4e5eb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_plan_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('image_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('img_perfect_prompt_list', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
        batch_op.drop_column('plan_introduction')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_plan_detail', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan_introduction', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('img_perfect_prompt_list')
        batch_op.drop_column('image_list')
        batch_op.drop_column('tag_list')

    # ### end Alembic commands ###
