"""add_conversation_plan_detail

Revision ID: ad2b4b4e5eb8
Revises: 2570a921fc64
Create Date: 2024-03-17 11:46:36.932394

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad2b4b4e5eb8'
down_revision = '2570a921fc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_plan_detail',
    sa.Column('id', postgresql.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('conversation_id', postgresql.UUID(), nullable=False),
    sa.Column('plan', sa.Text(), nullable=False),
    sa.Column('plan_introduction', sa.Text(), nullable=True),
    sa.Column('plan_detail_list', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('plan_conversation_history', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id', name='conversation_plan_detail_pkey')
    )
    with op.batch_alter_table('conversation_plan_detail', schema=None) as batch_op:
        batch_op.create_index('conversation_plan_detail_conversation_id_idx', ['conversation_id'], unique=False)
        batch_op.create_index('conversation_plan_detail_plan_idx', ['plan'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_plan_detail', schema=None) as batch_op:
        batch_op.drop_index('conversation_plan_detail_plan_idx')
        batch_op.drop_index('conversation_plan_detail_conversation_id_idx')

    op.drop_table('conversation_plan_detail')
    # ### end Alembic commands ###
