"""create plan_question

Revision ID: e316be27d39c
Revises: 426df5c160f0
Create Date: 2024-03-17 02:09:56.974966

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e316be27d39c"
down_revision = "426df5c160f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_question",
        sa.Column("id", postgresql.UUID(), server_default=sa.text("uuid_generate_v4()"), nullable=False),
        sa.Column("plan", sa.Text(), nullable=False),
        sa.Column("questions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP(0)"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP(0)"), nullable=False),
        sa.PrimaryKeyConstraint("id", name="plan_question_pkey"),
    )
    with op.batch_alter_table("plan_question", schema=None) as batch_op:
        batch_op.create_index("plan_question_tenant_id_idx", ["plan"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plan_question", schema=None) as batch_op:
        batch_op.drop_index("plan_question_tenant_id_idx")

    op.drop_table("plan_question")
    # ### end Alembic commands ###
