# base image
FROM python:3.10-slim-bookworm AS base

LABEL maintainer="takatost@gmail.com"

RUN pip install https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.7.3/en_core_web_trf-3.7.3.tar.gz
